services:
  db:
    image: mariadb:latest
    container_name: my-solid-app-mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my_solid_app_root_password
      MYSQL_DATABASE: my_solid_app_db
      MYSQL_USER: my_solid_app_user
      MYSQL_PASSWORD: my_solid_app_password

  redis:
    image: redis:latest
    container_name: my-solid-app-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  mail:
    image: maildev/maildev
    container_name: my-solid-app-maildev
    command:
      - "--incoming-user=mysolidapp@mail.com"
      - "--incoming-pass=12345678"
    ports:
      - "1080:1080"
      - "1025:1025"
