services:
  ui:
    image: $DOCKERHUB_NAMESPACE/my-solid-app-ui:latest
    container_name: my-solid-app-ui-staging
    volumes:
      - '/home/${MY_SOLID_APP_SERVER_USER}/certificates/:/etc/letsencrypt/'
      - '/home/${MY_SOLID_APP_SERVER_USER}/certbot/www:/var/www/certbot'
      - '/home/${MY_SOLID_APP_SERVER_USER}/nginx.staging.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '8080:80'
      - '8443:443'
    networks:
      - my-solid-app-network-staging
    depends_on:
      - api
    logging:
      driver: 'json-file'
      options:
        max-size: '5m'
        max-file: '10'

  api:
    image: $DOCKERHUB_NAMESPACE/my-solid-app-api:latest
    container_name: my-solid-app-api-staging
    environment:
      MY_SOLID_APP_DB_NAME: $MY_SOLID_APP_DB_NAME
      MY_SOLID_APP_DB_USER: $MY_SOLID_APP_DB_USER
      MY_SOLID_APP_DB_PASSWORD: $MY_SOLID_APP_DB_PASSWORD
      MY_SOLID_APP_DB_HOST: 'db'
      MY_SOLID_APP_DB_PORT: '3306'
      MY_SOLID_APP_FRONTEND_URL: https://staging.my-solid-app.nl:8443
      MY_SOLID_APP_PASSWORD_RESET_TOKEN_EXPIRE_HOURS: 1
      MY_SOLID_APP_SECRET_KEY: $MY_SOLID_APP_SECRET_KEY
      MY_SOLID_APP_MAIL_SERVER: $MY_SOLID_APP_MAIL_SERVER
      MY_SOLID_APP_MAIL_PORT: $MY_SOLID_APP_MAIL_PORT
      MY_SOLID_APP_MAIL_USE_SSL: 'True'
      MY_SOLID_APP_MAIL_USERNAME: $MY_SOLID_APP_MAIL_USERNAME
      MY_SOLID_APP_MAIL_PASSWORD: $MY_SOLID_APP_MAIL_PASSWORD
      MY_SOLID_APP_MAIL_DEFAULT_SENDER: $MY_SOLID_APP_MAIL_DEFAULT_SENDER
      MY_SOLID_APP_FERNET_SECRET_KEY: $MY_SOLID_APP_FERNET_SECRET_KEY
    networks:
      - my-solid-app-network-staging
    depends_on:
      - db
    logging:
      driver: 'json-file'
      options:
        max-size: '5m'
        max-file: '5'

  db:
    image: mariadb:latest
    container_name: my-solid-app-mariadb-staging
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MY_SOLID_APP_DB_NAME
      MYSQL_USER: $MY_SOLID_APP_DB_USER
      MYSQL_PASSWORD: $MY_SOLID_APP_DB_PASSWORD
    volumes:
      - db_data_staging:/var/lib/mysql
    networks:
      - my-solid-app-network-staging
    logging:
      driver: 'json-file'
      options:
        max-size: '5m'
        max-file: '5'

  certbot:
    image: certbot/certbot:latest
    container_name: my-solid-app-certbot-staging
    volumes:
      - '/home/${MY_SOLID_APP_SERVER_USER}/certificates/:/etc/letsencrypt/'
      - '/home/${MY_SOLID_APP_SERVER_USER}/certbot/lib-staging:/var/lib/letsencrypt/'
      - '/home/${MY_SOLID_APP_SERVER_USER}/certbot/www:/var/www/certbot'
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --force-renewal --webroot -w /var/www/certbot; sleep 30s & wait $${!}; done;'"
    networks:
      - my-solid-app-network-staging
    depends_on:
      - ui
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '3'

networks:
  my-solid-app-network-staging:
    driver: bridge


volumes:
  db_data_staging:
