import { createSignal, JSXElement, Show } from 'solid-js'
import api from '../api'
import { clsx } from 'clsx'
import { useUser } from '../context'

export function Disable2FAModal(): JSXElement {
  const { fetchUser } = useUser()
  const [totpCode, setTotpCode] = createSignal('')

  const [submitting, setSubmitting] = createSignal(false)
  const [errorMsg, setErrorMsg] = createSignal<string | null>(null)

  let disable2faModalRef: HTMLDialogElement | undefined

  const disable2fa = async () => {
    setErrorMsg(null)
    setSubmitting(true)

    api
      .post('/disable_2fa', { totp_code: totpCode() })
      .then(async () => {
        await fetchUser()
        disable2faModalRef?.close()
      })
      .catch((error) => {
        setErrorMsg(
          error.response.data.error_message ??
            'Could not disable 2FA. Please try again later.'
        )
      })
      .finally(() => {
        setSubmitting(false)
      })
  }

  return (
    <dialog ref={disable2faModalRef} id="disable_2fa_modal" class="modal">
      <div class="modal-box">
        <form method="dialog">
          <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-6">
            ✕
          </button>
        </form>

        <div>
          <h3 class="font-bold text-lg">Disable 2FA</h3>

          <p class="py-4">
            Enter the 6-digit code generated by your authenticator app.
          </p>

          <input
            type="text"
            class="input input-bordered w-full"
            placeholder=""
            value={totpCode()}
            onInput={(e) => setTotpCode(e.target.value)}
          />

          <Show when={errorMsg() !== null}>
            <div role="alert" class="alert alert-error mt-6">
              <span>{errorMsg()}</span>
            </div>
          </Show>

          <div class="modal-action">
            <button
              class={clsx('btn', 'btn-primary', submitting() && 'btn-disabled')}
              onClick={disable2fa}
            >
              <Show when={submitting()}>
                <span class="loading loading-spinner" />
              </Show>
              Disable 2FA
            </button>
          </div>
        </div>
      </div>
    </dialog>
  )
}
