import { JSXElement, createSignal, Show } from 'solid-js'
import { useNavigate, Link } from '@solidjs/router'
import { clsx } from 'clsx'

import { EmailIcon } from './icons/Email'
import { PasswordIcon } from './icons/Password'
import api from '../api'

import { User } from '../models/User'
import { useUser } from '../context'

export function LoginModal(): JSXElement {
  const { setUser } = useUser()
  const [email, setEmail] = createSignal<string | null>(null)
  const [password, setPassword] = createSignal<string | null>(null)
  const [errorMsg, setErrorMsg] = createSignal<string | null>(null)
  const [submitting, setSubmitting] = createSignal(false)

  const [totpCode, setTotpCode] = createSignal<string | null>(null)
  const [at2FAStep, setAt2FAStep] = createSignal(false)

  const navigate = useNavigate()

  let loginModalRef: HTMLDialogElement | undefined

  const formReady = () => {
    return email() !== null && password() !== null
  }

  const handlePasswordLogin = async () => {
    setSubmitting(true)

    api
      .post('/login', JSON.stringify({ email: email(), password: password() }))
      .then((response) => {
        const user = new User(response.data)
        if (user.twoFactorEnabled) {
          setAt2FAStep(true)
        } else {
          setUser(user)
          loginModalRef?.close()
          onClose()
          navigate('/home')
        }
      })
      .catch((error) => {
        setErrorMsg(error.response.data.error_message)
      })
      .finally(() => {
        setSubmitting(false)
      })
  }

  const handle2FALogin = async () => {
    setSubmitting(true)

    api
      .post(
        '/login_2fa',
        JSON.stringify({ email: email(), totp_code: totpCode() })
      )
      .then((response) => {
        setUser(new User(response.data))
        loginModalRef?.close()
        onClose()
        navigate('/home')
      })
      .catch((error) => {
        setErrorMsg(error.response.data.error_message)
      })
      .finally(() => {
        setSubmitting(false)
      })
  }

  const onClose = () => {
    setEmail(null)
    setPassword(null)
    setErrorMsg(null)
    setSubmitting(false)
    setTotpCode(null)
    setAt2FAStep(false)
  }

  return (
    <dialog ref={loginModalRef} id="login_modal" class="modal">
      <div class="modal-box">
        <h3 class="flex justify-center text-lg font-bold mb-6">Login</h3>

        <form method="dialog">
          <button
            class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2"
            onClick={onClose}
          >
            ✕
          </button>
        </form>

        <label class="input input-bordered flex items-center gap-2 mb-3">
          <EmailIcon />
          <input
            type="text"
            class="grow"
            placeholder="your@email.com"
            value={email()}
            disabled={at2FAStep()}
            onInput={(e) =>
              setEmail(e.target.value === '' ? null : e.target.value)
            }
          />
        </label>

        <label class="input input-bordered flex items-center gap-2">
          <PasswordIcon />
          <input
            type="password"
            class="grow"
            placeholder="Your password"
            value={password()}
            disabled={at2FAStep()}
            onInput={(e) =>
              setPassword(e.target.value === '' ? null : e.target.value)
            }
          />
        </label>

        <Show when={!at2FAStep()}>
          <Link
            class="flex justify-center text-primary mt-4"
            href="/forgot-password"
          >
            Forgot password?
          </Link>
        </Show>

        <Show when={at2FAStep()}>
          <p class="py-4">
            Enter the 6-digit code generated by your authenticator app.
          </p>

          <input
            type="text"
            class="input input-bordered w-full"
            placeholder=""
            value={totpCode()}
            onInput={(e) => setTotpCode(e.target.value)}
          />
        </Show>

        <Show when={errorMsg() !== null}>
          <div role="alert" class="alert alert-error my-6">
            <span>{errorMsg()}</span>
          </div>
        </Show>

        <Show when={!at2FAStep()}>
          <div class="modal-action flex justify-center">
            <button
              class={clsx(
                'btn',
                'btn-primary',
                (submitting() || !formReady()) && 'btn-disabled'
              )}
              onClick={handlePasswordLogin}
            >
              <Show when={submitting()}>
                <span class="loading loading-spinner" />
              </Show>
              Login
            </button>
          </div>
        </Show>

        <Show when={at2FAStep()}>
          <div class="modal-action flex justify-center">
            <button
              class={clsx(
                'btn',
                'btn-primary',
                (submitting() || totpCode().length !== 6) && 'btn-disabled'
              )}
              onClick={handle2FALogin}
            >
              <Show when={submitting()}>
                <span class="loading loading-spinner" />
              </Show>
              Login
            </button>
          </div>
        </Show>
      </div>
    </dialog>
  )
}
