import { JSXElement, createSignal, Show } from 'solid-js'
import { useNavigate, Link } from '@solidjs/router'
import { clsx } from 'clsx'

import {
  clearResponse,
  createForm,
  reset,
  minLength,
  maxLength,
  pattern,
  email,
  required,
  setResponse,
  SubmitHandler,
} from '@modular-forms/solid'

import { EmailIcon } from './icons/Email'
import { PasswordIcon } from './icons/Password'
import { passwordLogin, totpLogin } from '../api'

import { User } from '../models/User'
import { useUser } from '../context'
import { TextInput } from './TextInput'
import { Modal, ModalBaseProps } from './Modal'

type LoginFormData = {
  email: string
  password: string
}

type TotpFormData = {
  totpCode: string
}

export function LoginModal(props: ModalBaseProps): JSXElement {
  const { setUser } = useUser()
  const [currentEmail, setCurrentEmail] = createSignal<string | null>(null)
  const [loginForm, Login] = createForm<LoginFormData>()
  const [totpForm, Totp] = createForm<TotpFormData>()

  const [at2FAStep, setAt2FAStep] = createSignal(false)

  const navigate = useNavigate()

  let loginModalRef: HTMLDialogElement | undefined

  const onPasswordLogin: SubmitHandler<LoginFormData> = async (values) => {
    const response = await passwordLogin(values.email, values.password)

    if (response.status != 200) {
      setResponse(loginForm, {
        status: 'error',
        message: (await response.json()).error_message,
      })
      return
    }

    const data = await response.json()
    const user = new User(data)
    setResponse(loginForm, { status: 'success', data: data })
    setCurrentEmail(values.email)

    if (user.twoFactorEnabled) {
      setAt2FAStep(true)
    } else {
      setUser(user)
      loginModalRef?.close()
      onClose()
      navigate('/home')
    }
  }

  const onTotpLogin: SubmitHandler<TotpFormData> = async (values) => {
    const response = await totpLogin(currentEmail(), values.totpCode)

    if (response.status != 200) {
      setResponse(totpForm, {
        status: 'error',
        message: (await response.json()).error_message,
      })
      return
    }

    const data = await response.json()
    const user = new User(data)
    setResponse(loginForm, { status: 'success', data: data })

    setUser(user)
    loginModalRef?.close()
    onClose()
    navigate('/home')
  }

  const onClose = () => {
    clearResponse(loginForm)
    clearResponse(totpForm)
    reset(loginForm)
    reset(totpForm)
  }

  return (
    <Modal
      title="Login"
      isOpen={props.isOpen}
      onClose={() => {
        onClose()
        props.onClose()
      }}
    >
      <Login.Form onSubmit={onPasswordLogin}>
        <Login.Field
          name="email"
          validate={[
            required('Please enter your email'),
            email('The email address is badly formatted'),
          ]}
        >
          {(field, props) => (
            <TextInput
              {...props}
              type="email"
              value={field.value}
              error={field.error}
              placeholder="your@email.com"
              icon={<EmailIcon />}
            />
          )}
        </Login.Field>

        <Login.Field name="password">
          {(field, props) => (
            <TextInput
              {...props}
              type="password"
              value={field.value}
              error={field.error}
              placeholder="Password"
              icon={<PasswordIcon />}
            />
          )}
        </Login.Field>

        <Show when={loginForm.response.status === 'error'}>
          <div role="alert" class="alert alert-error my-4">
            <i class="fa-solid fa-circle-exclamation" />{' '}
            <span>{loginForm.response.message}</span>
          </div>
        </Show>

        <Show when={!at2FAStep()}>
          <Link
            class="flex justify-center text-primary mt-4"
            href="/forgot-password"
          >
            Forgot password?
          </Link>

          <div class="modal-action">
            <button
              class={clsx(
                'btn btn-primary',
                loginForm.submitting && 'btn-disabled'
              )}
              type="submit"
            >
              <Show when={loginForm.submitting} fallback="Login">
                <span class="loading loading-spinner" />
                Login
              </Show>
            </button>
          </div>
        </Show>
      </Login.Form>

      <Show when={at2FAStep()}>
        <div class="divider text-center mt-4" />

        <p class="pb-4">
          Enter the 6-digit code generated by your authenticator app.
        </p>

        <Totp.Form onSubmit={onTotpLogin}>
          <Totp.Field
            name="totpCode"
            validate={[
              required('Please enter a 6-digit code'),
              minLength(6, 'The code must be exactly 6 digits'),
              maxLength(6, 'The code must be exactly 6 digits'),
              pattern(/^\d{6}$/, 'The code must be exactly 6 digits'),
            ]}
          >
            {(field, props) => (
              <TextInput
                {...props}
                type="text"
                value={field.value}
                error={field.error}
                placeholder="123456"
              />
            )}
          </Totp.Field>

          <Show when={loginForm.response.status === 'error'}>
            <div role="alert" class="alert alert-error my-4">
              <i class="fa-solid fa-circle-exclamation" />{' '}
              <span>{loginForm.response.message}</span>
            </div>
          </Show>

          <div class="modal-action">
            <button
              class={clsx(
                'btn btn-primary',
                totpForm.submitting && 'btn-disabled'
              )}
              type="submit"
            >
              <Show when={totpForm.submitting} fallback="Login">
                <span class="loading loading-spinner" />
                Login
              </Show>
            </button>
          </div>
        </Totp.Form>
      </Show>
    </Modal>
  )
}
