apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../app

namespace: my-solid-app-prod

patches:
  - target:
      kind: Deployment
      name: my-solid-app-ui
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Ingress
      name: my-solid-app-ui
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: app.my-solid-app.com
      - op: replace
        path: /spec/rules/0/host
        value: app.my-solid-app.com
  - target:
      kind: Deployment
      name: my-solid-app-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Ingress
      name: my-solid-app-api
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.my-solid-app.com
      - op: replace
        path: /spec/rules/0/host
        value: api.my-solid-app.com

configMapGenerator:
  - name: my-solid-app-backend-config
    behavior: merge
    literals:
      - MY_SOLID_APP_FRONTEND_URL="https://app.my-solid-app.com"
      - MY_SOLID_APP_API_URL="https://api.my-solid-app.com"
      - MY_SOLID_APP_DB_NAME="my_solid_app_db"
      - MY_SOLID_APP_DB_HOST="<vps_ip>"
      - MY_SOLID_APP_MINIO_HOST="<object-storage-host>"
      - MY_SOLID_APP_MINIO_PORT=""
      - MY_SOLID_APP_MINIO_BUCKET="my-solid-app"
      - MY_SOLID_APP_MINIO_SECURE="True"

secretGenerator:
  - name: my-solid-app-backend-secrets
    literals:
      - MY_SOLID_APP_SECRET_KEY=${MY_SOLID_APP_SECRET_KEY}
      - MY_SOLID_APP_FERNET_SECRET_KEY=${MY_SOLID_APP_FERNET_SECRET_KEY}
      - MY_SOLID_APP_DB_USER=${MY_SOLID_APP_DB_USER}
      - MY_SOLID_APP_DB_PASSWORD=${MY_SOLID_APP_DB_PASSWORD}
      - MY_SOLID_APP_MAIL_SERVER=${MY_SOLID_APP_MAIL_SERVER}
      - MY_SOLID_APP_MAIL_USERNAME=${MY_SOLID_APP_MAIL_USERNAME}
      - MY_SOLID_APP_MAIL_PASSWORD=${MY_SOLID_APP_MAIL_PASSWORD}
      - MY_SOLID_APP_MAIL_DEFAULT_SENDER=${MY_SOLID_APP_MAIL_DEFAULT_SENDER}
      - MY_SOLID_APP_MOLLIE_API_KEY=${MY_SOLID_APP_MOLLIE_API_KEY}
      - MY_SOLID_APP_MINIO_USER=${MY_SOLID_APP_MINIO_USER}
      - MY_SOLID_APP_MINIO_PASSWORD=${MY_SOLID_APP_MINIO_PASSWORD}
