[tool.ruff]
line-length = 89
indent-width =4 

[tool.ruff.lint]
select = [
    # Pyflakes
    "F",
    # pycodestyle
    "E4",
    "E7",
    "E9",
    # isort
    "I",
    # pep8-naming
    "N",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    # Allow using star imports in __init__.py modules for giving easy access to
    # all exports defined in a package
    "F401", "F403", "F405",
]
